enh: configure AWS account password policy
maddevsio/aws-eks-base pull request #287
Opened 2022-05-09 11:42 UTC by mglotov

# PR Description

Configured AWS account password policy based on CIS recommendations. 

Fixes #286 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

2022-05-09 11:50 UTC, p1gmale0n requested changes

2022-05-09 11:50 UTC, p1gmale0n commented on terraform/layer1-aws/variables.tf
> +    hard_expiry                    = true # Whether users are prevented from setting a new password after their password has expired
i think this is too strict option.
without using aws web console, you may not notice the warnings.
and resetting the password will require the participation of the root account, which may take time

2022-05-09 12:06 UTC, p1gmale0n approved these changes

2022-05-11 07:02 UTC, khalezin approved these changes

2022-05-11 07:03 UTC, merged